import os
import struct
from pathlib import Path

BLOG_DIR = Path(r"D:\school website - Copy\jai-govind-school\public\images\blog")

# AI-related keywords to search for in metadata
AI_KEYWORDS = [
    b"synthid", b"SynthID", b"SYNTHID",
    b"midjourney", b"Midjourney", b"MIDJOURNEY",
    b"dall-e", b"DALL-E", b"dalle", b"DALLE",
    b"stable diffusion", b"Stable Diffusion", b"STABLE DIFFUSION",
    b"stable-diffusion", b"Stable-Diffusion",
    b"comfyui", b"ComfyUI",
    b"automatic1111", b"AUTOMATIC1111",
    b"flux", b"FLUX",
    b"imagen", b"Imagen", b"IMAGEN",
    b"firefly", b"Firefly", b"FIREFLY",
    b"generative", b"Generative", b"GENERATIVE",
    b"ai-generated", b"AI-generated", b"AI-Generated",
    b"ai generated", b"AI generated",
    b"generated by", b"Generated by",
    b"created with ai", b"Created with AI",
    b"ai image", b"AI image",
    b"prompt:", b"Prompt:",
    b"negative prompt", b"Negative prompt",
    b"steps:", b"Steps:",
    b"sampler:", b"Sampler:",
    b"cfg scale", b"CFG scale",
    b"seed:", b"Seed:",
    b"model:", b"Model:",
    b"loRA", b"LoRA", b"lora",
    b"checkpoint", b"Checkpoint",
    b"deepai", b"DeepAI",
    b"leonardo.ai", b"Leonardo",
    b"ideogram", b"Ideogram",
    b"playground", b"Playground",
    b"picfinder", b"PicFinder",
    b"adobe", b"Adobe Firefly",
    b"gemini", b"Gemini",
    b"imagen", b"Imagen",
    b"dreamstudio", b"DreamStudio",
    b"nightcafe", b"NightCafe",
    b"artbreeder", b"Artbreeder",
    b"this image was generated", b"This image was generated",
    b"artificial intelligence", b"Artificial Intelligence",
    b"neural network", b"Neural Network",
    b"diffusion model", b"Diffusion Model",
    b"GAN", b"generative adversarial",
    b"text-to-image", b"Text-to-Image",
    b"txt2img", b"img2img",
    b"a1111", b"webui",
    b"sd-webui", b"forge",
]

# Also check for Google DeepMind SynthID specific patterns
SYNTHID_PATTERNS = [
    b"synthid", b"SynthID", b"SYNTHID",
    b"deepmind", b"DeepMind", b"DEEPMIND",
    b"google.ai", b"Google AI",
    b"watermark", b"Watermark", b"WATERMARK",
    b"digimarc", b"Digimarc",
    b"Truepic", b"truepic",
    b"C2PA", b"c2pa", b"content credentials",
    b"Content Credentials",
    b"contentcredentials",
]

def check_file(filepath):
    """Check a single file for AI generation markers."""
    findings = []
    
    try:
        with open(filepath, 'rb') as f:
            data = f.read()
        
        # Check for AI keywords
        found_ai = []
        for keyword in AI_KEYWORDS:
            if keyword in data:
                found_ai.append(keyword.decode('utf-8', errors='ignore'))
        
        # Check for SynthID/watermark patterns
        found_synth = []
        for pattern in SYNTHID_PATTERNS:
            if pattern in data:
                found_synth.append(pattern.decode('utf-8', errors='ignore'))
        
        # Check file size - very small files might be AI-generated with low quality
        file_size = os.path.getsize(filepath)
        
        # Check for EXIF-like structures
        has_exif = b"Exif" in data[:1000] or b"EXIF" in data[:1000]
        has_xmp = b"xmp" in data[:5000].lower() or b"XMP" in data[:5000]
        has_iptc = b"IPTC" in data[:5000] or b"iptc" in data[:5000]
        
        # Check for JPEG/PNG/AVIF signatures
        is_avif = data[:12] == b'\x00\x00\x00\x1cftypavif' or b'avif' in data[:50]
        is_jpeg = data[:2] == b'\xff\xd8'
        is_png = data[:8] == b'\x89PNG\r\n\x1a\n'
        is_webp = data[:4] == b'RIFF' and data[8:12] == b'WEBP'
        
        fmt = "AVIF" if is_avif else "JPEG" if is_jpeg else "PNG" if is_png else "WEBP" if is_webp else "UNKNOWN"
        
        return {
            "file": filepath.name,
            "size_kb": round(file_size / 1024, 1),
            "format": fmt,
            "has_exif": has_exif,
            "has_xmp": has_xmp,
            "has_iptc": has_iptc,
            "ai_keywords": found_ai,
            "synthid_patterns": found_synth,
            "is_suspicious": len(found_ai) > 0 or len(found_synth) > 0,
        }
    except Exception as e:
        return {"file": filepath.name, "error": str(e)}

def main():
    avif_files = sorted(BLOG_DIR.glob("*.avif"))
    webp_files = sorted(BLOG_DIR.glob("*.webp"))
    
    print(f"Found {len(avif_files)} AVIF files and {len(webp_files)} WebP files")
    print("=" * 80)
    
    suspicious = []
    clean = []
    
    for f in avif_files + webp_files:
        result = check_file(f)
        if "error" in result:
            print(f"ERROR: {result['file']} - {result['error']}")
            continue
        
        if result["is_suspicious"]:
            suspicious.append(result)
        else:
            clean.append(result)
    
    # Print suspicious files
    if suspicious:
        print(f"\n{'='*80}")
        print(f"SUSPICIOUS FILES ({len(suspicious)} found):")
        print(f"{'='*80}")
        for r in suspicious:
            print(f"\n  File: {r['file']}")
            print(f"  Format: {r['format']} | Size: {r['size_kb']} KB")
            print(f"  EXIF: {r['has_exif']} | XMP: {r['has_xmp']} | IPTC: {r['has_iptc']}")
            if r['ai_keywords']:
                print(f"  AI Keywords: {', '.join(r['ai_keywords'])}")
            if r['synthid_patterns']:
                print(f"  SynthID/Watermark: {', '.join(r['synthid_patterns'])}")
    else:
        print(f"\nNo AI generation markers found in any image.")
    
    # Print summary of clean files
    print(f"\n{'='*80}")
    print(f"CLEAN FILES ({len(clean)} total):")
    print(f"{'='*80}")
    
    # Group by format
    formats = {}
    for r in clean:
        fmt = r['format']
        if fmt not in formats:
            formats[fmt] = []
        formats[fmt].append(r)
    
    for fmt, files in formats.items():
        sizes = [f['size_kb'] for f in files]
        print(f"\n  {fmt}: {len(files)} files")
        print(f"    Size range: {min(sizes):.1f} KB - {max(sizes):.1f} KB")
        print(f"    Avg size: {sum(sizes)/len(sizes):.1f} KB")
        exif_count = sum(1 for f in files if f['has_exif'])
        xmp_count = sum(1 for f in files if f['has_xmp'])
        print(f"    With EXIF: {exif_count} | With XMP: {xmp_count}")
    
    # Check if any files have metadata at all
    print(f"\n{'='*80}")
    print("METADATA ANALYSIS:")
    print(f"{'='*80}")
    no_metadata = [r for r in clean if not r['has_exif'] and not r['has_xmp'] and not r['has_iptc']]
    has_metadata = [r for r in clean if r['has_exif'] or r['has_xmp'] or r['has_iptc']]
    print(f"  Files WITH metadata: {len(has_metadata)}")
    print(f"  Files WITHOUT any metadata: {len(no_metadata)}")
    if no_metadata:
        print(f"  Note: {len(no_metadata)} files have NO metadata - this is common for")
        print(f"  AI-generated images or heavily compressed/optimized images.")

if __name__ == "__main__":
    main()
